
[System_Info]
PC_Update          = 1
FW_Version         = -
Viewer_Version     = ICBB_PC_0010 
Max_Channel        = 2
Max_Resolution     = 1280

[Display]
Language           = 0 ; 	0:English 1:Korean
TimeZone           = 9 ; 	(+9 : Korea)
UnitOfSpeed        = 0 ; 	0:km/h	  1:mile/h	2:knot
Disp_Mode          = 3 ; 	0:OFF     1:Front Camera  2:Rear Camera  3:Dual Mode_1  4:Dual Mode_2
Video_Type         = 0 ; 	0:NTSC    1:PAL


[Record]
Driving_2ch        = 0 ; 	0:Disable 1:Enable (Driving mode change to 2-channel record)
Channel            = 2 ; 	1:1CH(FRONT) 2:2CH        3:1CH(REAR)  
Mode               = 1 ; 	0:CONTINUOUS 1:EVENT
Type               = 1 ; 	0:MPEG4   1:H.264
Resolution_Ch1     = 1 ; 	0:D1      1:HD      
Quality_ch1        = 4 ; 	0:LOWEST  1:LOW     2:NORMAL  3:HIGH    4:HIGHEST 
Resolution_Ch2     = 1 ; 	0:D1      1:HD      
Quality_ch2        = 4 ; 	0:LOWEST  1:LOW     2:NORMAL  3:HIGH    4:HIGHEST 

# Quality (D1 Mode Video Bitrate - Lowest:1Mbps ~ Highest:3Mbps, 0.5Mbps step)
# Quality (HD Mode Video Bitrate - Lowest:3Mbps ~ Highest:8Mbps, 1.25Mbps step)

Audio              = 1 ; 	0:OFF	  1:ON
Event_Proportion   = 1 ; 	0:1/2	  1:1/3 	2:1/4	  3:1/5


[Device]
Parking_Record_Alarm = 1 ; 	0:OFF     1:Shock Event  2:Shock + Motion Event
Speaker_Volume     = 3 ; 	0 ~ 4
Usb_Mode           = 1 ; 	0:MODE1   1:MODE2   2:MODE3
# USB MODE : MODE1-USB Only, MODE2-Normal USB/Event SD, MODE3-USB/SD Equal

Record_Alarm       = 3 ; 	0:OFF     1:RECORD  2:PARKING_RECORD 3:PARKING_SHOCK
# Record Alarm(EXT_MODULE_GPO Low/High control): 0 OFF(do not use), 1 RECORD(Start recording, set to High)
# 2 PARKING_RECORD(When a Parking mode and event(with motion) is detected, set to High)
# 3 PARKING_SHOCK(When a parking mode and shock event is detected, set to High)

[Accelerometer]
Trigger_Level      = 0.30 ;	0.1 ~ 1.0  (0.2:HIGH 0.5:NORMAL 0.8:LOW, UNIT:g)

[MotionDetect_Ch1]
Mode               = 1 ;	0:OFF	  1:ON
Sensitive          = 1 ;	0 ~ 2 (0:HIGH	1:NORMAL	2:LOW)

[MotionDetect_Ch2]
Mode               = 1 ;	0:OFF	  1:ON
Sensitive          = 1 ;	0 ~ 2 (0:HIGH	1:NORMAL	2:LOW)


[System]
Buzzer_Mode        = 2 ;	0:OFF	  1:SYSTEM	2:SYSTEM + KEY 3:SYSTEM + EVENT 4:ALL ON
LowVoltageMode     = 1 ;	0:DUAL     1:VOLTAGE (0 DUAL:Sensing the voltage and power, 1 VOLTAGE:Sensing the voltage)
LowVoltageDetect   = 9.0 ;	9.0V ~ 12.6V(21.0 ~ 24.6V)
Parking_Mode       = 0 ;	0:OFF	  1:AUTO
Parking_Time       = 3 ;	1 ~ 10 Minute (Parking mode entry times)
Parking_USB        = 1 ;	0:OFF	  1:ON    	2:AUTO
Parking_UsbOffVolt = 0.3 ;	0.2 ~ 1.0V (When setting a Parking_USB AUTO mode operation, LowVoltage + UsbOffVolt)
Parking_LowPower   = 2 ;	0:OFF	  1:ON    	2:AUTO
# Parking low power mode : OFF-30FPS, ON-15FPS(25% Power save), AUTO-Event ready 15FPS / Event 30FPS


[Time]
Year                = 2014 ;
Month               = 9 ;
Date                = 16 ;
Hour                = 0 ;
Minute              = 0 ;
Sec                 = 0 ;
Time_Set            = 0 ; 	0:NOT SET 1:SET
