//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BBPlayer.rc
//
#define MODEL_DAVIEW_2CH                0
#define LANGUAGE_ENGLISH                0
#define MODEL_DAVIEW_2CH_L              1
#define LANGUAGE_KOREAN                 1
#define MODEL_DAVIEW_2CH_F              2
#define LANGUAGE_JAPANESE               2
#define MODEL_DAVIEW_2CH_S              3
#define MODEL_NH_200A                   4
#define MODEL_BW_2000                   5
#define MODEL_Q_BLACK                   6
#define MODEL_KIC_M7                    7
#define MODEL_HONDA_HD_2U               8
#define MODEL_SAMPLE                    9
#define MODEL_ITSG_HD_2U                10
#define MODEL_TMPD_HD_2U                11
#define MODEL_ICARO_I300HD              12
#define MODEL_VIEW_I_2U                 13
#define MODEL_DOOCO_M7                  14
#define MODEL_RALLY_EYES                15
#define MODEL_EYE_TRACKS                16
#define IDD_TEMPLATE                    103
#define IDD_MAIN_DLG                    104
#define IDR_HTML_LOGDLG                 105
#define IDR_MAINFRAME                   128
#define IDD_SELDRIVE_DLG                131
#define IDD_GSENSOR_DLG                 132
#define IDD_NOTIFY_DLG                  133
#define IDD_SETTING_DLG                 134
#define IDD_SELMODEL_DLG                135
#define IDD_LOG_DLG                     136
#define IDD_ABOUT_DLG                   137
#define IDD_COPYFILE                    138
#define IDD_REPORT                      139
#define IDD_NXFSFORMATTER_DIALOG        140
#define IDD_PASSWORD                    141
#define IDD_PASSWORD_SETTING            142
#define IDC_MAIN_BTN_SAVEALL            1000
#define IDC_MAIN_BTN_SET                1001
#define IDC_MAIN_BTN_LOG                1002
#define IDC_MAIN_BTN_CAPTURE            1003
#define IDC_MAIN_BTN_ABOUT              1004
#define IDC_MAIN_BTN_SITE               1005
#define IDC_MAIN_VIDEO_FRONT            1006
#define IDC_MAIN_WEB_MAP                1007
#define IDC_MAIN_VIDEO_REAR             1008
#define IDC_MAIN_BTN_MINIMIZE           1009
#define IDC_MAIN_BTN_MAXIMIZE           1010
#define IDC_MAIN_BTN_NORMALIZE          1011
#define IDC_MAIN_BTN_EXIT               1012
#define IDC_MAIN_BTN_VIDEOCHANGE        1013
#define IDC_MAIN_BTN_FINF               1014
#define IDC_MAIN_BTN_RINF               1015
#define IDC_MAIN_BTN_RINM               1016
#define IDC_MAIN_BTN_NORMAL             1017
#define IDC_MAIN_BTN_EVENT              1018
#define IDC_MAIN_BTN_MANUAL             1019
#define IDC_MAIN_BTN_MOTION             1020
#define IDC_MAIN_SLD_TIME               1021
#define IDC_MAIN_IMAGE_FILE             1022
#define IDC_MAIN_TEXT_FILE              1023
#define IDC_MAIN_TEXT_CURTIME           1024
#define IDC_MAIN_TEXT_DURATION          1025
#define IDC_MAIN_IMAGE_SPEED0           1026
#define IDC_MAIN_SLD_SPEED              1027
#define IDC_MAIN_IMAGE_SPEED1           1028
#define IDC_MAIN_IMAGE_BRIGHT           1029
#define IDC_MAIN_SLD_BRIGHT             1030
#define IDC_MAIN_IMAGE_VOLUME           1031
#define IDC_MAIN_BTN_FRCHANGE           1032
#define IDC_MAIN_BTN_FINR               1033
#define IDC_MAIN_IMAGE_MUTE             1034
#define IDC_MAIN_BTN_FINM               1035
#define IDC_MAIN_SLD_VOLUME             1036
#define IDC_MAIN_BTN_PREV               1037
#define IDC_MAIN_BTN_PLAY               1038
#define IDC_MAIN_BTN_STOP               1039
#define IDC_MAIN_BTN_NEXT               1040
#define IDC_MAIN_BTN_REW                1041
#define IDC_MAIN_BTN_FF                 1042
#define IDC_MAIN_BTN_FPS                1043
#define IDC_MAIN_BTN_OPEN               1044
#define IDC_MAIN_BTN_SAVE               1045
#define IDC_MAIN_FILELIST               1046
#define IDC_MAIN_BTN_VOLUME             1047
#define IDC_MAIN_BTN_CAM_FF             1048
#define IDC_MAIN_GSENSOR_VIEW           1049
#define IDC_MAIN_BTN_FMCHANGE           1050
#define IDC_MAIN_BTN_ZOOM               1051
#define IDC_MAIN_VIDEO_ZOOM             1052
#define IDC_MAIN_BTN_CAM_FM             1053
#define IDC_MAIN_BTN_CAM_RF             1054
#define IDC_MAIN_BTN_CAM_RM             1055
#define IDC_MAIN_BTN_CHECKFILELISTALL   1056
#define IDC_NOTIFY_TXT_TITLE            1080
#define IDC_NOTIFY_TXT_COMMENT          1081
#define IDC_NOTIFY_BTN_SELOK            1082
#define IDC_NOTIFY_BTN_SELCANCEL        1083
#define IDC_MAIN_TEXT_LATITUDE          1084
#define IDC_MAIN_TEXT_LONGITUDE         1085
#define IDC_MAIN_TEXT_ALTITUDE          1086
#define IDC_MAIN_TEXT_GPS_SPEED         1087
#define IDC_MAIN_TEXT_SPEED             1088
#define IDC_MAIN_TEXT_BRIGHT            1089
#define IDC_SETTING_COMBO_DISP_TIMEZONE 1090
#define IDC_SETTING_COMBO_DISP_TIME_OFFSET 1091
#define IDC_SETTING_QUALITY_HIGH        1094
#define IDC_SETTING_QUALITY_MIDDLE      1095
#define IDC_SETTING_QUALITY_LOW         1096
#define IDC_SETTING_STATIC_VIDEO_QUALITY 1099
#define IDC_SETTING_STATIC_DISPLAY_TIMEZONE 1100
#define IDC_SETTING_STATIC_DISPLAY_TIMESET 1101
#define IDC_SETTING_STATIC_DISPLAY_TIMESET_VALUE 1102
#define IDC_SETTING_STATIC_RECORD_CHANNEL 1105
#define IDC_SETTING_STATIC_RECORD_AUDIO 1106
#define IDC_SETTING_STATIC_RECORD_CODEC 1107
#define IDC_SETTING_STATIC_RECORD_RESOLUTION 1108
#define IDC_SETTING_STATIC_SPEAKER_VOLUME 1109
#define IDC_SETTING_STATIC_ENGINE_CYLINDERS 1110  // jun 20201202
#define IDC_SETTING_STATIC_ENGINE_CYLINDERS_LOW 1111  // jun 20201202
#define IDC_SETTING_STATIC_ENGINE_CYLINDERS_NORMAL 1112  // jun 20201202
#define IDC_SETTING_STATIC_ENGINE_CYLINDERS_HIGH 1113  // jun 20201202
#define IDC_SETTING_RECORD_AUDIO_OFF    1114
#define IDC_SETTING_RECORD_AUDIO_ON     1115
#define IDC_SETTING_PULSE_RESET_OFF     1117
#define IDC_SETTING_PULSE_RESET_ON      1118
#define IDC_SETTING_STATIC_DEVICE       1120
#define IDC_SETTING_STATIC_DEVICE_GSENSOR_SENSITIVE 1121
#define IDC_SETTING_STATIC_DEVICE_GSENSOR_LOW 1123
#define IDC_SETTING_STATIC_DEVICE_GSENSOR_NORMAL 1124
#define IDC_SETTING_STATIC_DEVICE_GSENSOR_HIGH 1125
#define IDC_SETTING_EVENT_CAPACITY_A    1131
#define IDC_SETTING_EVENT_CAPACITY_B    1132
#define IDC_SETTING_EVENT_CAPACITY_C    1133
#define IDC_SETTING_STATIC_SPEAKER_VOLUME_VALUE 1150
#define IDC_SETTING_STATIC_DEVICE_GSENSOR_SENSITIVE_VALUE 1151
#define IDC_SETTING_STATIC_ENGINE_CYLINDERS_VALUE 1152  // jun 20201202
#define IDC_SETTING_TEXT_TITLE          1153
#define IDC_SETTING_STATIC_EVENT_CAPACITY 1159
#define IDC_SETTING_INIT                1204
#define IDC_SETTING_SAVE                1205
#define IDC_SETTING_CANCEL              1206
#define IDC_SETTING_SLD_SPEAKER_VOLUME  1207
#define IDC_SETTING_SLD_ENGINE_CYLINDERS         1209  // jun 20201202
#define IDC_SETTING_CLOSE               1208
#define IDC_SETTING_DEVICETIME          1213
#define IDC_SETTING_BTN_SETTIME         1214
#define IDC_SETTING_SLD_GSENSORSENS     1215
#define IDC_SETTING_BTN_DISKPART0       1216
#define IDC_SETTING_BTN_DISKPART1       1217
#define IDC_SETTING_BTN_DISKPART2       1218
#define IDC_SETTING_BTN_FORMAT          1219
#define IDC_SETTING_TEXT_DISPLAY        1221
#define IDC_SETTING_TEXT_DISPLAY_LANG   1222
#define IDC_SETTING_TEXT_DISPLAY_SPEED  1223
#define IDC_SETTING_TEXT_DISPLAY_TIMEZONE 1224
#define IDC_SETTING_TEXT_DISPLAY_TIMESET 1225
#define IDC_SETTING_TEXT_DISPLAY_TIME   1230
#define IDC_SETTING_STATIC_PULSERESET   1231
#define IDC_SETTING_BTN_PULSERESET      1232
#define IDC_SETTING_STATIC_PULSE_UD_TACHO1 1233
#define IDC_SETTING_STATIC_PULSE_UD_TACHO4 1234
#define IDC_SETTING_STATIC_PULSE_UD_TAHCO5 1235
#define IDC_SETTING_PULSE_UD_TACHO1_LOW 1236
#define IDC_SETTING_PULSE_UD_TACHO1_HIGH 1237
#define IDC_SETTING_PULSE_UD_TACHO4_LOW 1238
#define IDC_SETTING_PULSE_UD_TACHO4_HIGH 1239
#define IDC_SETTING_PULSE_UD_TACHO5_LOW 1240
#define IDC_SETTING_PULSE_UD_TACHO5_HIGH 1241
#define IDC_SETTING_BTN_PASSWORD        1242
#define IDC_SETTING_STATIC_CARNUMBER    1243
#define IDC_SETTING_STATIC_OSDSPEED     1244
#define IDC_SETTING_OSDSPEED_OFF        1245
#define IDC_SETTING_OSDSPEED_ON         1246
#define IDC_SETTING_STATIC_DRIVERCODE    1247
#define IDC_PASS_OLD                    1250
#define IDC_PASS_NEW                    1251
#define IDC_PASS_CONFIRM                1252
#define IDC_PASS_PASSWORD               1253
#define IDC_PASSWORD                    1254
#define IDC_EDIT_OLD_PASSWORD           1255
#define IDC_EDIT_NEW_PASSWORD           1256
#define IDC_EDIT_CONFIRM                1257
#define IDC_GSENSOR_TEXT_TITLE          1300
#define IDC_GSENSOR_GRAPH               1301
#define IDC_SELDRV_COMBDRV              1400
#define IDC_SELDRV_DRIVE                1401
#define IDC_SELDRV_TITLE                1402
#define IDC_SELMODEL_COMBMODEL          1500
#define IDC_SELMODEL_TEXT_MODEL         1501
#define IDC_SELMODEL_TEXT_TITLE         1502
#define IDC_SELMODEL_TEXT_COMMENT       1503
#define IDC_LOG_LIST                    1600
#define IDC_LOG_BTN_SAVE                1601
#define IDC_LOG_TEXT_TITLE              1602
#define IDC_COPYPROGRESS                1603
#define IDC_FILENAME                    1604
#define IDC_COPYDLG_STATIC_PAGE         1605
#define IDC_ABOUT_TEXT_VERVIEWER        1700
#define IDC_ABOUT_TEXT_VERFIRMWARE      1701
#define IDC_ABOUT_BTN_GOTOSITE          1703
#define IDC_ABOUT_TEXT_TITLE            1704
#define IDC_ABOUT_TEXT_TITLEVIEWER      1708
#define IDC_ABOUT_TEXT_TITLEFIRMWARE    1709
#define IDC_ABOUT_TEXT_COMMENTVIEWER    1710
#define IDC_ABOUT_TEXT_COMMENTFIRMWARE  1711
#define IDC_ABOUT_BTN_UPDATE_VIEWER     1712
#define IDC_ABOUT_BTN_UPDATE_FIRMWARE   1713
#define IDC_DATETIMEPICKER_TIME         1800
#define IDC_DATETIMEPICKER_DATE         1801
#define IDC_ICDBGRAPH_H                 1802
#define IDC_ICDBGRAPH_M                 1803
#define IDC_ICDBGRAPH_S                 1804
#define IDC_DIGIT_NUM_SPEED             1805
#define IDC_DIGIT_NUM_LATITUDE          1806
#define IDC_DIGIT_NUM_LONGITUDE         1807
#define IDC_MAIN_WEB_SPONSOR            1808
#define IDC_MAIN_BTN_PRINT              1809
#define IDC_STATIC_PREVIEW              1810
#define IDC_EDIT_MEMO                   1811
#define IDC_BTN_INSERT_MEMO             1812
#define IDC_BTN_PRINT                   1813
#define IDC_MAIN_BTN_FULL_F             1814
#define IDC_MAIN_BTN_FULL_R             1815
#define IDC_MAIN_BTN_FULL_M             1816
#define IDC_CANCEL                      1817
#define IDC_STATIC_REPORT               1818
#define IDC_MAIN_BTN_FORMAT             1819
#define IDC_FORMAT_CMB_SELDRIVE         1820
#define IDC_FORMAT_BTN_RELOAD           1821
#define IDC_FORMAT_STC_STORAGESTATE     1822
#define IDC_FORMAT_STC_PROGRESS         1823
#define IDC_FORMAT_PRG_FORMAT           1824
#define IDC_FORMAT_BTN_FORMAT           1825
#define IDC_FORMAT_STATIC_STORAGE_INFO  1826
#define IDC_FORMAT_STATIC_CAP           1827
#define IDC_FORMAT_BTN_OK               1828
#define IDC_MAIN_BTN_TACHO1             1829
#define IDC_MAIN_BTN_TACHO2             1830
#define IDC_MAIN_BTN_TACHO3             1831
#define IDC_MAIN_BTN_TACHO4             1832
#define IDC_MAIN_BTN_TACHO5             1833
#define IDC_MAIN_BTN_GPS_PULSE          1834
#define IDC_SETTING_EDIT_CARNUMBER      1837
#define IDC_DIGIT_NUM_RPM               1838
#define IDC_MAIN_VIDEO_QUADCTRL		1839
#define IDC_MAIN_VIDEO_QUADVIEW	1840
#define IDC_SETTING_EDIT_DRIVERCODE      1841
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1841
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
